services:
  web:
    build: .
    platform: linux/amd64
    expose:
      - 5001
    env_file:
      - ./.env
    init: true
    volumes:      
      - ./static/assets/data/structures:/static/assets/data/structures
      - ./static/assets/img/dps:/static/assets/img/dps
      - type: bind
        source: ./logs/
        target: /logs
  nginx:
    build: ./services/nginx
    platform: linux/arm64/v8
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    init: true
    depends_on:
      - web
      - shynet
  certbot:
    image: certbot/certbot
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    depends_on:
      - nginx
