services:
  web:
    build: .
    platform: linux/amd64
    expose:
      - 5001
    env_file:
      - ./.flaskenv
    init: true
  nginx:
    build: ./services/nginx
    platform: linux/arm64/v8
    ports:
      - 80:80
    init: true
    depends_on:
      - web
