services:
  web:
    build: .
    platform: linux/amd64
    expose:
      - 5001
    env_file:
      - ./.env
    init: true
    volumes:
      - type: bind
        source: ./logs/
        target: /logs
  nginx:
    build: ./services/nginx
    platform: linux/amd64
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    init: true
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
  shynet:
    container_name: shynet_main
    image: milesmcc/shynet:edge
    restart: unless-stopped
    expose:
      - 5010
    env_file:
      # Create a file called '.env' if it doesn't already exist.
      # You can use `TEMPLATE.env` as a guide.
      - .env
    volumes:
      - ./services/shynet_db/:/var/local/shynet/db:rw
  webserver:
    container_name: shynet_webserver
    image: nginx
    restart: always
    volumes:
      - ./services/shynet/nginx.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - 5010:80
    depends_on:
      - shynet
