[project]
name = "flask-site"
version = "0.1.0"
description = "Personal Flask site"
authors = [
    { name = "Tom Pekin", email = "tcpekin@gmail.com" },
]
dependencies = [
    "numpy>=1.26.4,<2.0",
    "py4dstem==0.13.17",
    "python-dotenv>=1.0.0",
    "gunicorn>=21.2.0",
    "flask-flatpages",
    "flask>=3.0.0",
    "pandas>=2.1.2",
    "plotly>=5.18.0",
    "scipy>=1.11.3",
    "pymatgen>=2023.8.10",
    "mp-api>=0.41.2",
    "h5py==3.10.0",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.0",
]

[tool.uv]
package = false
